[package]
name = "basic-blinker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arduino_nano33iot = "0.7.0"
panic-halt = "0.2.0"